### ISSUE TITLE
USER STORY: Site navigation

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#1]
As a **customer** I can **easily navigate through the site** so that **I can understand its purpose**

## Acceptance criteria:
1. The website must have a navigation bar that is easy to understand and use;
2. The customers can easily access what they want;
3. The website is simple and easy to understand its purpose.

## Tasks:

- [ ] Add a navigation bar;
- [ ] Add simple colors;
- [ ] Add information structured and simple to use;
- [ ] Use images and colors from the same scheme;
- [ ] Create buttons/shortcuts for the reservations.
