### ISSUE TITLE
USER STORY: Admin - tables reservation

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#12]
As an **admin** I can **I can see how many tables have been reserved** so that **I can know how many people will be in the restaurant**

## Acceptance criteria:
1. The admin account should have all the bookings made;
2. The admin can consult all the reservations;
3. The admin can easily manage all reservations.

## Tasks:

- [ ] Create a consult option to reservations;
- [ ] Create a update option to reservations;
- [ ] Create a cancel option to reservations;
- [ ] Send a email to the customer with the new information;
- [ ] Update register client bookings;
- [ ] Test functionality.
