### ISSUE TITLE
USER STORY: Admin - special requirements from customers

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#13]
As an **admin** I can **I can see what special requirements my customers added when they booked the table** so that **I can respond to those requests**

## Acceptance criteria:
1. The admin account should have all special requirements made;
2. The admin can consult all the special requirements;
3. The admin can easily manage all reservations.

## Tasks:

- [ ] Create a consult option to special requirements;
- [ ] If the admin made any changes to the client reservation: Send a email to the customer with the new information;
- [ ] If the admin made any changes to the client reservation: Update register client bookings;
- [ ] If the admin made any changes to the client reservation: Update admin reservations view;
- [ ] Test functionality.
