### ISSUE TITLE
USER STORY: Admin account - reservations management

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#14]
As an **admin**,through my account, I can **view, modify or cancel reservations** so that **I can manage the reservations for each day**

## Acceptance criteria:
1. The admin account should have all the reservations made;
2. The admin can consult all the special requirements;
3. The admin can easily manage or change all reservations.

## Tasks:

- [ ] If the admin made any changes to the client reservation: Send a email to the customer with the new information;
- [ ] If the admin made any changes to the client reservation: Update register client bookings;
- [ ] If the admin made any changes to the client reservation: Update admin reservations view;
- [ ]  If the customer made any changes: Update admin reservations view;
- [ ]  If the customer made any changes: Send a email to the admin email with the new information;
- [ ] Test functionality.
