### ISSUE TITLE
USER STORY: Menu

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#2]
As a **customer** I can **have access to the menu** so that **I know what food the restaurant offer**

## Acceptance criteria:
1. The website must have a menu easy to understand;
2. The customers can easily access the menu;
3. The website is simple and easy to understand its purpose.

## Tasks:

- [ ] Create a menu;
- [ ] Create a nav bar with access to the menu;
- [ ] Add information structured and simple to understand;
- [ ] Add the option for download the menu.
