### ISSUE TITLE
Location page

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#3]
As a **customer** I can **see a location tab** so that **I can know here the restaurant is located**

## Acceptance criteria:
1. The website must have location tab in the navigation bar;
2. The customers can easily access what the location tab;
3. The location tab is simple to use and easy to understand.

## Tasks:

- [ ] Add location tab to nav bar;
- [ ] Add location address;
- [ ] Add location phone number and email;
- [ ] Add location map.
