### ISSUE TITLE
USER STORY: About us page

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#4]
As a **customer** I can **see a little description about the restaurant** so that **I can know more about the restaurant history**

## Acceptance criteria:
1. The website must have a about us page;
2. The about us page explains the restaurant history;
3. The About us page is simple, structure and easy to understand.

## Tasks:

- [ ] Add a About us page to nav bar;
- [ ] Create the text of the About us page;
- [ ] Add a image;
- [ ] Test the page responsiveness.
