### ISSUE TITLE
USER STORY: Customer booking - number of people

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#7]
As a **customer** I can **choose how many people I want in my reservation** so that **I can have a table suitable for the number of people**

## Acceptance criteria:
1. The website must have booking system;
2. The customers can easily how many people they want their reservation;
3. The booking system is simple and easy to understand.

## Tasks:

- [ ] Add a reservation tab to nav bar;
- [ ] Create a add number of people option;
- [ ] Create a booking system form;
- [ ] Send to the client a email with the booking confirmation;
- [ ] Update register client bookings;
- [ ] Test the functionality.
