### ISSUE TITLE
USER STORY: Customer booking - special requirements

### ISSUE THREAD

**Issue by joanavrsilva** [joanavrsilva/Italian-gold-restaurant#8]
As a **customer** I can **leave special requirements on my reservation** so that **I can communicate them to the restaurant**

## Acceptance criteria:
1. The website must have booking system;
2. The customers can easily leave special requirements on their reservation;
3. The booking system is simple and easy to understand.

## Tasks:

- [ ] Add a reservation tab to nav bar;
- [ ] Create a leave special requirements option;
- [ ] Create a booking system form;
- [ ] Send to the client a email with the booking confirmation;
- [ ] Update register client bookings;
- [ ] Test the functionality.
